### ISSUE TITLE
No SU Dialog

### ISSUE THREAD

**Issue by boswelja** [AospExtended/platform_frameworks_base-old#10]
If I remove SuperSU and enable root access via Developer Options, theres no dialog?

**Comment by AmolAmrit** [comment]
Because it's already granting permissions by default

**Comment by boswelja** [comment]
@AmolAmrit I figured that much, but why is it doing that?

**Comment by AmolAmrit** [comment]
I guess it's set by default. I remembered CM's root was similar

**Comment by ishubhamsingh** [comment]
Ya it isn't working due to some mismerges...that's why i am using superSU.Even logs didn't helped.
